version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  userservice:
    build: .
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=usersdb;Username=postgres;Password=yourpassword"
    ports:
      - "8080:80"
volumes:
  pgdata:
